### ISSUE TITLE
在？

### ISSUE THREAD

**Issue by KiteAB** [PikachuHy/Oak-Pokemon-Research-Lab#1]
把我的视频链接移除吧  那个视频删了（笑哭

**Comment by PikachuHy** [comment]
哪个东西？

**Comment by KiteAB** [comment]
emmmm 有点抽象  等等  我找找那个位置

**Comment by KiteAB** [comment]
https://github.com/PikachuHy/Oak-Pokemon-Research-Lab/blob/8506705ca5f20c5ad5ac809660abbc4fd76389de/deepin/deepin-weekly/README.md  345行

**Comment by PikachuHy** [comment]
已经删除了

**Comment by KiteAB** [comment]
没删啊

**Comment by PikachuHy** [comment]
你看最新版 
https://github.com/PikachuHy/Oak-Pokemon-Research-Lab/tree/master/deepin/deepin-weekly

**Comment by KiteAB** [comment]
可
